server:
  port:  8081
  
spring:
 datasource:
   url:  jdbc:mysql://localhost:3306/microservicios
   username: root
   password: Hadm1995..
   driver: com.myslq.jc.jdbc.Driver
   
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate:
      dialect:  org.hibernate.dialect.MySQL8Dialect